### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by dev210202** [jkey20/ERRS#5]
1. 관리자 앱 아이콘 변경
- [x] uiid -> token 변경
- [x] 메뉴 페이지
- [x] qr 코드 인식 후 앱 연결
- [x] 관리자 - 알림 발송
- [x] 사용자 - 알림 수신
- [x] 관리자 로그인
- [x] 스플래쉬 페이지
- [ ] 에러처리

관리자: 메뉴 업로드
